// Доменные типы страниц с секциями живут в @forge/shared (общие с backend).
// Реэкспорт даёт стабильный путь `@/domain/page` для www.
export type {
    Page,
    PageSection,
    PageSectionType,
    PageSectionDataMap,
    AboutHeroData,
    ProductionHeroData,
    FinanceHeroData,
    ContactsHeroData,
    WorksHeroData,
    GuaranteeHeroData,
    LegalHeroData,
    CardGridData,
    ValueListData,
    StringListData,
    BulletSectionsData,
    RequisitesTableData,
    LeadFormData,
    TeamData,
    TimelineData,
    CtaLinksData,
    LocationCardsData,
    WorksMapData,
    SectionHeadingData,
    CardItem,
    ValueLabel,
    LabelValue,
    PageLink,
} from "@forge/shared";
