export const FALLBACK_HOME_SLOTS: Record<string, string> = {
    "hero.banner": "/media/hero/banner.jpg",
    "hero.fargo": "/media/hero/fargo.jpg",
    "hero.hill": "/media/hero/hill.jpg",
    "hero.visit": "/media/hero/visit.jpg",
    "hero.own-project": "/media/hero/own-project.jpg",
    "hero.kiskelovo": "/media/hero/kiskelovo.jpg",
    "tech.thumb.0": "/media/projects/reyn.jpg",
    "tech.thumb.1": "/media/projects/arkada.jpg",
    "tech.thumb.2": "/media/projects/kasl.jpg",
    "tech.gas_concrete.house": "/media/tech/gas_concrete/house.png",
    "tech.gas_concrete.sample-a": "/media/tech/gas_concrete/sample-a.jpg",
    "tech.gas_concrete.sample-b": "/media/tech/gas_concrete/sample-b.jpg",
    "tech.brick.house": "/media/tech/brick/house.png",
    "tech.brick.sample-a": "/media/tech/brick/sample-a.jpg",
    "tech.brick.sample-b": "/media/tech/brick/sample-b.jpg",
    "tech.frame.house": "/media/tech/frame/house.png",
    "tech.frame.sample-a": "/media/tech/frame/sample-a.jpg",
    "tech.frame.sample-b": "/media/tech/frame/sample-b.jpg",
    "tech.sip.house": "/media/tech/sip/house.png",
    "tech.sip.sample-a": "/media/tech/sip/sample-a.jpg",
    "tech.sip.sample-b": "/media/tech/sip/sample-b.jpg",
    "tech.fachwerk.house": "/media/tech/fachwerk/house.png",
    "tech.fachwerk.sample-a": "/media/tech/fachwerk/sample-a.jpg",
    "tech.fachwerk.sample-b": "/media/tech/fachwerk/sample-b.jpg",
    "collection.second_light": "/media/collections/second_light.jpg",
    "collection.panorama": "/media/collections/panorama.jpg",
    "collection.flat_roof": "/media/collections/flat_roof.jpg",
    "collection.garage": "/media/collections/garage.jpg",
    "collection.terrace": "/media/collections/terrace.jpg",
    "services.visit": "/media/services/visit-house.jpg",
    "built.0": "/media/built-strip/01.jpg",
    "built.1": "/media/built-strip/02.jpg",
    "built.2": "/media/built-strip/03.jpg",
    "built.3": "/media/built-strip/04.jpg",
    "built.4": "/media/built-strip/05.jpg",
    "built.5": "/media/built-strip/06.jpg",
    "built.6": "/media/built-strip/07.jpg",
    "blog.0": "/media/blog/start-survey.jpg",
    "blog.1": "/media/blog/tech-materials.jpg",
    "blog.2": "/media/blog/foundation-crack.jpg",
    "stages.plot": "/media/stages/plot.jpg",
    "stages.site": "/media/stages/site.jpg",
    "stages.facade": "/media/stages/facade.jpg",
    "stages.interior": "/media/stages/interior.jpg",
    "lead.office": "/media/lead/office.jpg",
};

export function slotUrl(slots: Record<string, string>, slot: string): string {
    return slots[slot] ?? FALLBACK_HOME_SLOTS[slot] ?? "";
}
